version: '3.2'

services:

  todo-test:
    container_name: "back-test"
    build: .
    hostname: "todo-test"
    links:
      - mongodb-test
    depends_on:
      - mongodb-test
    volumes:
      - $PWD/server:/usr/src/app
    working_dir: "/usr/src/app"
    command: "go run main.go"
    networks:
      - backend-test
    ports:
      - 8080:8080

  mongodb-test:
    image: "mongo:latest"
    container_name: "mongodb-test"
    hostname: "mongodb-test"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongo
        #      - MONGODB_USER="root"
        #      - MONGODB_PASS="password"
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend-test
    #    environment:
            #      MONGO_INITDB_ROOT_USERNAME: root
            #      MONGO_INITDB_ROOT_PASSWORD: password
      #    command: mongodb --smallfiles --logpath=/var/log/mongo

networks:
  backend-test:

